version: 2.1

parameters:
   pkg_name:
      type: string
      default: "testsrunner"
   repo_name:
      type: string
      default: "testsrunner"
   last_stable:
      type: string
      default: "8.2"
   user:
      type: string
      default: "cdat"
   label:
      type: string
      default: "nightly"
   env_name:
      type: string
      default: "test_testsrunner"


aliases:
  - &setup_env
    name: setup_env
    command: |
       echo 'export WORKDIR=/home/circleci/project/workdir' >> $BASH_ENV
       source $BASH_ENV
       mkdir -p $WORKDIR

  - &setup_miniconda
    name: setup_miniconda
    command: |
       source $BASH_ENV
       mkdir -p $WORKDIR
       git clone -b validateNightlyNew https://github.com/CDAT/cdat.git $WORKDIR/cdat
       # install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python $WORKDIR/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &conda_rerender
    name: conda_rerender
    command: |
       source $BASH_ENV
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       make conda-rerender conda=$WORKDIR/miniconda/bin/conda workdir=$WORKDIR last_stable=$LAST_STABLE branch=$CIRCLE_BRANCH

  - &conda_build
    name: conda_build
    command: |
       source $BASH_ENV
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       make conda-build conda=$WORKDIR/miniconda/bin/conda workdir=$WORKDIR artifact_dir=$PWD/artifacts

  - &setup_run_tests
    name: setup_run_tests
    command: |
       source $BASH_ENV
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       export CONDA_PY_VER="python=$PY_VER"

       make setup-tests conda=$WORKDIR/miniconda/bin/conda conda_env=$ENV_NAME extra_pkgs="$CONDA_PY_VER $COVERAGE_PKGS"
       make conda-dump-env conda=$WORKDIR/miniconda/bin/conda conda_env=$ENV_NAME artifact_dir=spec_artifacts conda_env_filename=$CIRCLE_JOB


  - &run_tests
    name: run_tests
    command: |
       source $BASH_ENV
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate $ENV_NAME
       make run-tests conda=$WORKDIR/miniconda/bin/conda conda_env=$ENV_NAME
    no_output_timeout: 20m

  - &conda_upload
    name: conda_upload
    command: |
       source $BASH_ENV
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base

       UPLOAD_OPTIONS="conda_upload_token=$CONDA_UPLOAD_TOKEN user=$USER label=$LABEL"
       make conda-upload $UPLOAD_OPTIONS conda=$WORKDIR/miniconda/bin/conda artifact_dir="$PWD/artifacts/"

  - &run_coveralls
    name: run_coveralls
    command: |
       source $BASH_ENV
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate $ENV_NAME
       coveralls
       conda deactivate

executors:
   linux:
      machine:
         image: circleci/classic:latest
   macos:
      macos:
         xcode: "11.4.0"

jobs:
   build_test:
      machine:
         image: circleci/classic:latest
      environment:
         PKG_NAME: << pipeline.parameters.pkg_name >>
         REPO_NAME: << pipeline.parameters.repo_name >>
         LAST_STABLE: << pipeline.parameters.last_stable >>
         ENV_NAME: << pipeline.parameters.env_name >>
         PY_VER: "3.7"
      steps:
         - checkout
         - run: *setup_env
         - run: *setup_miniconda
         - run: *conda_rerender
         - run: *conda_build
         - run: *setup_run_tests
         - run: *run_tests
         - persist_to_workspace:
              root: .
              paths: 
                 - workdir
                 - artifacts
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
              path: tests_png
              destination: tests_png
         - store_artifacts:
              path: spec_artifacts
              destination: spec_artifacts

   upload:
      machine:
         image: circleci/classic:latest
      environment:
         USER: << pipeline.parameters.user >>
         LABEL: << pipeline.parameters.label >>
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_env
         - run: *conda_upload

workflows:
   testsrunner:
      jobs:
         - build_test
         - upload:
              requires:
                 - build_test
