#!/usr/bin/env python
import testsrunner
import argparse

parser = argparse.ArgumentParser(description="Compare two images")
parser.add_argument("image1", help="Path to the first image")
parser.add_argument("image2", help="Path to the second image")

args = parser.parse_args()
testsrunner.view_images(args.image1, args.image2)
